### ISSUE TITLE
Added devdependency to React 17 in 4.0.5

### ISSUE THREAD

**Issue by drjonnicholson** [what3words/w3w-node-wrapper#43]
Hi,

Just wondering why the additional dev dependency to React 17 in version 4.0.5? I assume this library should be framework agnostic?

**Comment by c5haw** [comment]
Hi @drjonnicholson - yes this library is framework agnostic. The dev dependency, which is not shipped or required for use in production is purely for testing the app in a browser environment as we had some recent issues that surfaced when using this library in a browser environment.

React, JS-DOM and React Testing Library have been used in conjunction to simulate a browser environment so that we could deterministically recreate the browser environment issue and ensure that it no longer is a bug and should not resurface as this is now included in the tests as part of our CI pipeline.

**Comment by drjonnicholson** [comment]
THanks
